---
  # This playbook is executed by Vagrant or  Ansible Tower to configure
  # new hosts once they have been provisioned.

  - name: Configure Meteor Hosts
    hosts: tuxlab-meteor
    sudo: yes
    roles:
      - rhel
      - nodejs
      - meteor
      - tuxlab-app

  - name: Configure Swarm Hosts
    hosts: tuxlab-swarm-host:tuxlab-swarm-manager
    roles:
      - atomichost
      - dockerhost

  - name: Configure Swarm Manager
    hosts: tuxlab-swarm-manager
    roles:
    - atomichost
    - dockerswarm
